In [1]:
import pandas as pd
from datetime import datetime
import os
import psycopg2
from sqlalchemy import create_engine, text
from decouple import config
from dotenv import load_dotenv
import json
import sys
sys.path.append('C:\\Users\\PC\\Documents\\Matias\\torneos_primera_division_arg')
from db import *

postgresql://matiasmazparrotefeliu:***@postgresql-matiasmazparrotefeliu.alwaysdata.net:5432/matiasmazparrotefeliu_etl_data_practise

In [2]:
df_selected_teams = pd.DataFrame()
try:
    with engine.connect():
        print("CONNECTED TO POSTGRESQL DATABASE")
        query = text('SELECT * FROM torneos_primera_arg."Selected_teams"')
        df = pd.read_sql_query(query, engine)
        df_selected_teams = pd.concat([df_selected_teams, df], ignore_index=True)
except Exception as e:
    print(f"Error: {e}")
    print("READING CSV DATA")
    df = pd.read_csv('../CSV/Selected_teams.csv')
    df_selected_teams = pd.concat([df_selected_teams, df], ignore_index=True)
df_selected_teams

CONNECTED TO POSTGRESQL DATABASE

,nombre,pais,año,code,data
0,Racing_Club,Argentina,"2015,2018,2020,2022,2024",E1,"[{""Unnamed: 0"": 0, ""date"": ""15 Dic 14"", ""statu..."

In [3]:
for column in df_selected_teams.columns:
    if 'Unnamed' in column:
        df_selected_teams.drop(column, inplace=True, axis=1)

In [4]:
df_selected_teams['data'] = df_selected_teams['data'].apply(json.loads)

In [5]:
print(df_selected_teams.info())
df_selected_teams

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  1 non-null      object
 1   pais    1 non-null      object
 2   año     1 non-null      object
 3   code    1 non-null      object
 4   data    1 non-null      object
dtypes: object(5)
memory usage: 168.0+ bytes
None

,nombre,pais,año,code,data
0,Racing_Club,Argentina,"2015,2018,2020,2022,2024",E1,"[{'Unnamed: 0': 0, 'date': '15 Dic 14', 'statu..."

In [6]:
data = df_selected_teams['data']
df_teams_matchs = pd.DataFrame()
for listt in data:
    df = pd.json_normalize(listt)
    df_teams_matchs = pd.concat([df_teams_matchs, df], ignore_index=True)

In [7]:
df_teams_matchs.head()

,Unnamed: 0,date,status,home_team,away_team,link,tournament,score,goles_local,goles_visitante,amarillas_local,amarillas_visitante,code,año,team,local_scorers,away_scorers,local_yellow_cards,away_yellow_cards,year
0,0,15 Dic 14,Finalizado,Racing Club,Godoy Cruz,https://www.resultados-futbol.com/partido/Raci...,Torneo de Transición 2014,1-0,R. Centurión,NaN,R. Centurión,"F. Lértora, R. Garcia, R. Ramírez, D. Rodrígue...",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
1,1,30 Nov 14,Finalizado,Rosario Central,Racing Club,https://www.resultados-futbol.com/partido/Ca-R...,Torneo de Transición 2014,0-3,NaN,"Gastón Díaz, D. Milito, D. Milito","Y. Gómez, Franco Cervi",G. Hauche,E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
2,2,24 Nov 14,Finalizado,Racing Club,River Plate,https://www.resultados-futbol.com/partido/Raci...,Torneo de Transición 2014,1-0,R. Funes Mori,NaN,"L. Aued, N. Sánchez, L. Grimi","Guido Rodríguez, E. Mammana, M. Barovero, B. U...",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
3,3,16 Nov 14,Finalizado,Quilmes,Racing Club,https://www.resultados-futbol.com/partido/Quil...,Torneo de Transición 2014,0-1,NaN,G. Bou,A. Alegre,"Y. Cabral, L. Lollo, G. Bou",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
4,4,09 Nov 14,Finalizado,Racing Club,Banfield,https://www.resultados-futbol.com/partido/Raci...,Torneo de Transición 2014,1-0,G. Bou,NaN,E. Videla,"G. Toledo, W. Erviti",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN

In [8]:
for column in df_teams_matchs.columns:
    if 'Unnamed' in column:
        df_teams_matchs.drop(column, inplace=True, axis=1)

In [9]:
months_list = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 
               'Octubre', 'Noviembre', 'Diciembre']
months_list = [{'number': i + 1, 'month': month} for i, month in enumerate(months_list)]
def normalize_date(row):
    date = row['date']
    day = int(date[0:2])
    month = date[3:6]
    year = date[7:9]
    for i, month_ in enumerate(months_list):
        if month in months_list[i]['month']:
            date_normalized = datetime(int('20'+year), month_['number'], day)
            return date_normalized

In [10]:
df_teams_matchs['date'] = df_teams_matchs.apply(normalize_date, axis=1)

In [11]:
df_teams_matchs.head()

,date,status,home_team,away_team,link,tournament,score,goles_local,goles_visitante,amarillas_local,amarillas_visitante,code,año,team,local_scorers,away_scorers,local_yellow_cards,away_yellow_cards,year
0,2014-12-15,Finalizado,Racing Club,Godoy Cruz,https://www.resultados-futbol.com/partido/Raci...,Torneo de Transición 2014,1-0,R. Centurión,NaN,R. Centurión,"F. Lértora, R. Garcia, R. Ramírez, D. Rodrígue...",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
1,2014-11-30,Finalizado,Rosario Central,Racing Club,https://www.resultados-futbol.com/partido/Ca-R...,Torneo de Transición 2014,0-3,NaN,"Gastón Díaz, D. Milito, D. Milito","Y. Gómez, Franco Cervi",G. Hauche,E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
2,2014-11-24,Finalizado,Racing Club,River Plate,https://www.resultados-futbol.com/partido/Raci...,Torneo de Transición 2014,1-0,R. Funes Mori,NaN,"L. Aued, N. Sánchez, L. Grimi","Guido Rodríguez, E. Mammana, M. Barovero, B. U...",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
3,2014-11-16,Finalizado,Quilmes,Racing Club,https://www.resultados-futbol.com/partido/Quil...,Torneo de Transición 2014,0-1,NaN,G. Bou,A. Alegre,"Y. Cabral, L. Lollo, G. Bou",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN
4,2014-11-09,Finalizado,Racing Club,Banfield,https://www.resultados-futbol.com/partido/Raci...,Torneo de Transición 2014,1-0,G. Bou,NaN,E. Videla,"G. Toledo, W. Erviti",E1,2015.0,Racing_Club,NaN,NaN,NaN,NaN,NaN

In [12]:
df_teams_matchs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1134 entries, 0 to 1133
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 1134 non-null   datetime64[ns]
 1   status               1134 non-null   object
 2   home_team            1134 non-null   object
 3   away_team            1134 non-null   object
 4   link                 1134 non-null   object
 5   tournament           1132 non-null   object
 6   score                1132 non-null   object
 7   goles_local          805 non-null    object
 8   goles_visitante      686 non-null    object
 9   amarillas_local      945 non-null    object
 10  amarillas_visitante  994 non-null    object
 11  code                 1134 non-null   object
 12  año                  1085 non-null   float64
 13  team                 1134 non-null   object
 14  local_scorers        8 non-null      object
 15  away_scorers         10 non-null     object
 16  local_yellow_cards   15 non-null     object
 17  away_yellow_cards    15 non-null     object
 18  year                 49 non-null     float64
dtypes: datetime64[ns](1), float64(2), object(16)
memory usage: 168.5+ KB